// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OJTHub.Server.Data;

#nullable disable

namespace OJTHub.Server.Migrations
{
    [DbContext(typeof(OJTHubDbContext))]
    [Migration("20260921135037_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OJTHub.Server.Models.ActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("HoursSpent")
                        .HasColumnType("decimal(3,1)");

                    b.Property<string>("TaskTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("OJTHub.Server.Models.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<int>("LunchBreakMinutes")
                        .HasColumnType("integer");

                    b.Property<decimal?>("NetRenderedHours")
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("SupervisorRemark")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("TimeIn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TimeInDistance")
                        .HasColumnType("decimal(6,1)");

                    b.Property<decimal>("TimeInGpsAccuracy")
                        .HasColumnType("decimal(5,1)");

                    b.Property<decimal>("TimeInLatitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("TimeInLongitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<bool>("TimeInWithinGeofence")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("TimeOut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("TimeOutDistance")
                        .HasColumnType("decimal(6,1)");

                    b.Property<decimal?>("TimeOutGpsAccuracy")
                        .HasColumnType("decimal(5,1)");

                    b.Property<decimal?>("TimeOutLatitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("TimeOutLongitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<bool?>("TimeOutWithinGeofence")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VerifiedBySupervisorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VerifiedBySupervisorId");

                    b.HasIndex("UserId", "Date");

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("OJTHub.Server.Models.GeneratedReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiGeneratedContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EditedContent")
                        .HasColumnType("text");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("RawPromptData")
                        .HasColumnType("text");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("GeneratedReports");
                });

            modelBuilder.Entity("OJTHub.Server.Models.OjtSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("DailyScheduleHours")
                        .HasColumnType("decimal(4,1)");

                    b.Property<int>("DefaultLunchMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("GeofenceRadiusMeters")
                        .HasColumnType("integer");

                    b.Property<int>("GpsAccuracyThreshold")
                        .HasColumnType("integer");

                    b.Property<decimal>("TargetTotalHours")
                        .HasColumnType("decimal(5,1)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("WorkplaceLatitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("WorkplaceLongitude")
                        .HasColumnType("decimal(9,6)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("OjtSettings");
                });

            modelBuilder.Entity("OJTHub.Server.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StudentId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SupervisorCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("SupervisorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SupervisorCode")
                        .IsUnique();

                    b.HasIndex("SupervisorId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OJTHub.Server.Models.ActivityLog", b =>
                {
                    b.HasOne("OJTHub.Server.Models.User", "User")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OJTHub.Server.Models.AttendanceRecord", b =>
                {
                    b.HasOne("OJTHub.Server.Models.User", "User")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OJTHub.Server.Models.User", "VerifiedBySupervisor")
                        .WithMany()
                        .HasForeignKey("VerifiedBySupervisorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");

                    b.Navigation("VerifiedBySupervisor");
                });

            modelBuilder.Entity("OJTHub.Server.Models.GeneratedReport", b =>
                {
                    b.HasOne("OJTHub.Server.Models.User", "User")
                        .WithMany("GeneratedReports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OJTHub.Server.Models.OjtSetting", b =>
                {
                    b.HasOne("OJTHub.Server.Models.User", "User")
                        .WithOne("OjtSetting")
                        .HasForeignKey("OJTHub.Server.Models.OjtSetting", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OJTHub.Server.Models.User", b =>
                {
                    b.HasOne("OJTHub.Server.Models.User", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("OJTHub.Server.Models.User", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("AttendanceRecords");

                    b.Navigation("GeneratedReports");

                    b.Navigation("OjtSetting");
                });
#pragma warning restore 612, 618
        }
    }
}
